const express = require("express");
const router = express.Router();
const userController = require("../controller/user-controller");
router.get("/voucher-held", userController.getVoucherHeld);
router.get("/:id", userController.getUserById);
router.get("/", userController.getAllUsers);
router.put("/", userController.updateUserById);
router.post("/test", userController.test);
router.delete("/:id", userController.deleteAllByUser);
module.exports = router;
